#pragma once
#include <array>

namespace PixelMapper {

struct Preset {
    const char* name;
    const char* glsl;
};

// ─────────────── Preset GLSL Shaders ────────────────────────────
// All shaders expect:
//   uniform float time;
//   uniform vec2  resolution;
//   in vec3 vPixelPos3D;
//   in vec2 vPixelPos2D;
//   out vec4 fragColor;

static constexpr const char* GLSL_HEADER =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n\n";

static constexpr const char* GLSL_PLASMA =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "void main() {\n"
    "    float x = iPixelPos2D.x * 10.0;\n"
    "    float y = iPixelPos2D.y * 10.0;\n"
    "    float v1 = sin(x + time);\n"
    "    float v2 = sin(10.0 * (x * sin(time / 2.0) + y * cos(time / 3.0)) + time);\n"
    "    float cx = x + 5.0 * sin(time / 5.0);\n"
    "    float cy = y + 5.0 * cos(time / 3.0);\n"
    "    float v3 = sin(sqrt(cx*cx + cy*cy + 1.0) - time);\n"
    "    float v = (v1 + v2 + v3) / 3.0;\n"
    "    float r = sin(v * 3.1415) * 0.5 + 0.5;\n"
    "    float g = sin(v * 3.1415 + 2.094) * 0.5 + 0.5;\n"
    "    float b = sin(v * 3.1415 + 4.188) * 0.5 + 0.5;\n"
    "    fragColor = vec4(r, g, b, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_HORIZONTAL_SWEEP =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "void main() {\n"
    "    float speed = 0.5;\n"
    "    float sweep = mod(time * speed, 1.0);\n"
    "    float bar   = smoothstep(sweep - 0.04, sweep, iPixelPos2D.x)\n"
    "                - smoothstep(sweep, sweep + 0.04, iPixelPos2D.x);\n"
    "    float bg = 0.05;\n"
    "    float brightness = bg + bar * (1.0 - bg);\n"
    "    fragColor = vec4(brightness, brightness, brightness * 0.8, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_VERTICAL_CHASE =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "void main() {\n"
    "    float speed = 0.5;\n"
    "    float sweep = mod(time * speed, 1.0);\n"
    "    float bar   = smoothstep(sweep - 0.04, sweep, iPixelPos2D.y)\n"
    "                - smoothstep(sweep, sweep + 0.04, iPixelPos2D.y);\n"
    "    float bg = 0.05;\n"
    "    float brightness = bg + bar * (1.0 - bg);\n"
    "    fragColor = vec4(brightness * 0.8, brightness, brightness, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_RAINBOW_WAVE =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "vec3 hsv2rgb(vec3 c) {\n"
    "    vec4 K = vec4(1.0, 2.0/3.0, 1.0/3.0, 3.0);\n"
    "    vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);\n"
    "    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);\n"
    "}\n"
    "void main() {\n"
    "    float hue = iPixelPos2D.x + time * 0.1;\n"
    "    vec3 col = hsv2rgb(vec3(mod(hue, 1.0), 1.0, 1.0));\n"
    "    fragColor = vec4(col, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_FIRE =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "float hash(vec2 p) { return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }\n"
    "float noise(vec2 p) {\n"
    "    vec2 i = floor(p); vec2 f = fract(p);\n"
    "    vec2 u = f * f * (3.0 - 2.0 * f);\n"
    "    return mix(mix(hash(i), hash(i+vec2(1,0)), u.x),\n"
    "               mix(hash(i+vec2(0,1)), hash(i+vec2(1,1)), u.x), u.y);\n"
    "}\n"
    "void main() {\n"
    "    vec2 q = iPixelPos2D;\n"
    "    q.y = 1.0 - q.y;  // flame rises upward\n"
    "    float t = time * 1.5;\n"
    "    float f = noise(q * vec2(3.0, 5.0) + vec2(0.0, -t));\n"
    "    f += 0.5 * noise(q * vec2(6.0, 10.0) + vec2(0.0, -t * 1.3));\n"
    "    f = clamp(f - q.y * 1.1, 0.0, 1.0);\n"
    "    vec3 fire = mix(vec3(1.0, 0.0, 0.0), vec3(1.0, 0.9, 0.0), f);\n"
    "    fire = mix(vec3(0.0), fire, pow(f, 0.4));\n"
    "    fragColor = vec4(fire, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_SPARKLE =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "float hash(vec2 p) { return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }\n"
    "void main() {\n"
    "    vec2 cell = floor(iPixelPos2D * 20.0);\n"
    "    float rnd  = hash(cell + floor(time * 12.0));\n"
    "    float spark = step(0.94, rnd);\n"
    "    fragColor = vec4(vec3(spark), 1.0);\n"
    "}\n";

static constexpr const char* GLSL_COLOR_SOLID =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "vec3 hsv2rgb(vec3 c) {\n"
    "    vec4 K = vec4(1.0, 2.0/3.0, 1.0/3.0, 3.0);\n"
    "    vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);\n"
    "    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);\n"
    "}\n"
    "void main() {\n"
    "    float hue = mod(time * 0.05, 1.0);\n"
    "    vec3 col = hsv2rgb(vec3(hue, 0.9, 1.0));\n"
    "    fragColor = vec4(col, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_BREATHING =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "void main() {\n"
    "    float breathe = sin(time * 1.2) * 0.5 + 0.5;\n"
    "    breathe = breathe * breathe;  // ease\n"
    "    fragColor = vec4(breathe, breathe * 0.85, breathe * 1.0, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_STROBE =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "void main() {\n"
    "    float hz = 4.0;  // strobe frequency\n"
    "    float on = step(0.5, fract(time * hz));\n"
    "    fragColor = vec4(on, on, on, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_VOLUMETRIC_SPHERE =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "uniform vec3 pixelPosMin;\n"
    "uniform vec3 pixelPosMax;\n"
    "\n"
    "void main() {\n"
    "    vec3 pMin = pixelPosMin;\n"
    "    vec3 pMax = pixelPosMax;\n"
    "    if (distance(pMin, pMax) < 1.0) {\n"
    "        pMin = vec3(-200.0, -100.0, -100.0);\n"
    "        pMax = vec3(200.0, 100.0, 100.0);\n"
    "    }\n"
    "    vec3 center = mix(pMin, pMax, vec3(\n"
    "        0.5 + 0.3 * sin(time * 1.5),\n"
    "        0.5 + 0.3 * cos(time * 1.0),\n"
    "        0.5 + 0.3 * sin(time * 2.0)\n"
    "    ));\n"
    "    float dist = distance(iPixelPos3D, center);\n"
    "    \n"
    "    float maxRadius = 0.5 * distance(pMin, pMax);\n"
    "    float radius = mod(time * 150.0, maxRadius);\n"
    "    float thickness = 40.0;\n"
    "    float wave = smoothstep(thickness, 0.0, abs(dist - radius));\n"
    "    \n"
    "    vec3 col = vec3(0.5 + 0.5 * sin(iPixelPos3D.x * 0.005 + time),\n"
    "                    0.5 + 0.5 * sin(iPixelPos3D.y * 0.005 + time * 1.2),\n"
    "                    0.5 + 0.5 * sin(iPixelPos3D.z * 0.005 + time * 1.5));\n"
    "    fragColor = vec4(col * wave, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_VOLUMETRIC_WAVE =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "uniform vec3 pixelPosMin;\n"
    "uniform vec3 pixelPosMax;\n"
    "\n"
    "void main() {\n"
    "    vec3 dir = normalize(vec3(1.0, 0.4, 0.7));\n"
    "    float proj = dot(iPixelPos3D, dir);\n"
    "    \n"
    "    float spatialFreq = 0.01;\n"
    "    float speed = 6.0;\n"
    "    float wave = sin(proj * spatialFreq - time * speed) * 0.5 + 0.5;\n"
    "    \n"
    "    vec3 col = vec3(0.5 + 0.5 * sin(proj * 0.003 + time),\n"
    "                    0.5 + 0.5 * sin(proj * 0.003 + time + 2.09),\n"
    "                    0.5 + 0.5 * sin(proj * 0.003 + time + 4.18));\n"
    "    fragColor = vec4(col * wave, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_VOLUMETRIC_NOISE =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "uniform vec3 pixelPosMin;\n"
    "uniform vec3 pixelPosMax;\n"
    "\n"
    "float hash(vec3 p) {\n"
    "    p = fract(p * vec3(443.8975, 397.2973, 491.1871));\n"
    "    p += dot(p.xyz, p.yzx + 19.19);\n"
    "    return fract(p.x * p.y * p.z);\n"
    "}\n"
    "float noise(vec3 p) {\n"
    "    vec3 i = floor(p);\n"
    "    vec3 f = fract(p);\n"
    "    vec3 u = f * f * (3.0 - 2.0 * f);\n"
    "    return mix(\n"
    "        mix(mix(hash(i + vec3(0,0,0)), hash(i + vec3(1,0,0)), u.x),\n"
    "            mix(hash(i + vec3(0,1,0)), hash(i + vec3(1,1,0)), u.x), u.y),\n"
    "        mix(mix(hash(i + vec3(0,0,1)), hash(i + vec3(1,0,1)), u.x),\n"
    "            mix(hash(i + vec3(0,1,1)), hash(i + vec3(1,1,1)), u.x), u.y), u.z);\n"
    "}\n"
    "void main() {\n"
    "    vec3 coord = iPixelPos3D * 0.005 - vec3(0.0, time * 0.2, time * 0.1);\n"
    "    float n = noise(coord) * 0.6 + noise(coord * 2.5) * 0.4;\n"
    "    vec3 col1 = vec3(0.1, 0.8, 0.95);\n"
    "    vec3 col2 = vec3(0.9, 0.0, 0.55);\n"
    "    vec3 finalColor = mix(col1, col2, n);\n"
    "    float intensity = smoothstep(0.35, 0.75, n);\n"
    "    fragColor = vec4(finalColor * intensity, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_VOLUMETRIC_HELIX =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "uniform vec3 pixelPosMin;\n"
    "uniform vec3 pixelPosMax;\n"
    "\n"
    "void main() {\n"
    "    float x = iPixelPos3D.x;\n"
    "    float y = iPixelPos3D.y;\n"
    "    float z = iPixelPos3D.z;\n"
    "    \n"
    "    float pitch = 180.0;\n"
    "    float radius = 90.0;\n"
    "    float angle = (x / pitch) * 2.0 * 3.14159 + time * 3.0;\n"
    "    \n"
    "    float ey1 = sin(angle) * radius;\n"
    "    float ez1 = cos(angle) * radius;\n"
    "    float ey2 = sin(angle + 3.14159) * radius;\n"
    "    float ez2 = cos(angle + 3.14159) * radius;\n"
    "    \n"
    "    float d1 = distance(vec2(y, z), vec2(ey1, ez1));\n"
    "    float d2 = distance(vec2(y, z), vec2(ey2, ez2));\n"
    "    \n"
    "    float thickness = 25.0;\n"
    "    float strand1 = smoothstep(thickness, 0.0, d1);\n"
    "    float strand2 = smoothstep(thickness, 0.0, d2);\n"
    "    \n"
    "    vec3 col = vec3(1.0, 0.15, 0.05) * strand1 + vec3(0.05, 0.35, 1.0) * strand2;\n"
    "    fragColor = vec4(col, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_VOLUMETRIC_BREATHING_SPHERE =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "void main() {\n"
    "    float dist = length(iPixelPos3D);\n"
    "    float radius = mix(50.0, 300.0, 0.5 + 0.5 * sin(time * 1.5));\n"
    "    float intensity = smoothstep(radius + 15.0, radius - 15.0, dist);\n"
    "    vec3 color = vec3(0.5 + 0.5 * sin(time),\n"
    "                      0.5 + 0.5 * sin(time + 2.09),\n"
    "                      0.5 + 0.5 * sin(time + 4.18));\n"
    "    fragColor = vec4(color * intensity, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_VOLUMETRIC_SPINNING_BOX =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "void main() {\n"
    "    float angle = time * 1.0;\n"
    "    float c = cos(angle), s = sin(angle);\n"
    "    vec3 pos = iPixelPos3D;\n"
    "    float rx = pos.x * c - pos.z * s;\n"
    "    float rz = pos.x * s + pos.z * c;\n"
    "    vec3 rotPos = vec3(rx, pos.y, rz);\n"
    "    \n"
    "    vec3 halfExtents = vec3(250.0, 50.0, 250.0);\n"
    "    float insideX = smoothstep(halfExtents.x + 10.0, halfExtents.x - 10.0, abs(rotPos.x));\n"
    "    float insideY = smoothstep(halfExtents.y + 10.0, halfExtents.y - 10.0, abs(rotPos.y));\n"
    "    float insideZ = smoothstep(halfExtents.z + 10.0, halfExtents.z - 10.0, abs(rotPos.z));\n"
    "    float intensity = insideX * insideY * insideZ;\n"
    "    \n"
    "    vec3 color = vec3(1.0, 0.5, 0.1);\n"
    "    fragColor = vec4(color * intensity, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_VOLUMETRIC_CYLINDER_SLICER =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "void main() {\n"
    "    vec3 pos = iPixelPos3D;\n"
    "    float angle = time * 1.5;\n"
    "    float c = cos(angle), s = sin(angle);\n"
    "    float ry = pos.y * c - pos.z * s;\n"
    "    float rz = pos.y * s + pos.z * c;\n"
    "    \n"
    "    float distYZ = length(vec2(ry, rz));\n"
    "    float inCylinder = smoothstep(210.0, 190.0, distYZ);\n"
    "    float inX = smoothstep(310.0, 290.0, abs(pos.x));\n"
    "    \n"
    "    float phi = atan(rz, ry);\n"
    "    float inWedge = smoothstep(0.25, 0.15, abs(phi));\n"
    "    \n"
    "    float intensity = inCylinder * inX * inWedge;\n"
    "    vec3 color = vec3(0.1, 0.8, 1.0);\n"
    "    fragColor = vec4(color * intensity, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_VOLUMETRIC_TORUS =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "void main() {\n"
    "    float pitch = time * 0.8;\n"
    "    float yaw = time * 1.2;\n"
    "    float cp = cos(pitch), sp = sin(pitch);\n"
    "    float cy = cos(yaw), sy = sin(yaw);\n"
    "    vec3 p = iPixelPos3D;\n"
    "    \n"
    "    float ryx = p.x * cy - p.z * sy;\n"
    "    float ryz = p.x * sy + p.z * cy;\n"
    "    vec3 pRotY = vec3(ryx, p.y, ryz);\n"
    "    \n"
    "    float rzx = pRotY.x;\n"
    "    float rzy = pRotY.y * cp - pRotY.z * sp;\n"
    "    float rzz = pRotY.y * sp + pRotY.z * cp;\n"
    "    vec3 rotP = vec3(rzx, rzy, rzz);\n"
    "    \n"
    "    float R = 180.0;\n"
    "    float r = 30.0;\n"
    "    float q = length(rotP.xy) - R;\n"
    "    float dist = length(vec2(q, rotP.z));\n"
    "    float intensity = smoothstep(r + 10.0, r - 10.0, dist);\n"
    "    \n"
    "    vec3 color = vec3(0.9, 0.1, 0.9);\n"
    "    fragColor = vec4(color * intensity, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_VOLUMETRIC_CONE =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "void main() {\n"
    "    float angle = time * 1.2;\n"
    "    vec3 dir = normalize(vec3(cos(angle), sin(angle * 0.8), -1.0));\n"
    "    vec3 pos = iPixelPos3D;\n"
    "    float proj = dot(pos, dir);\n"
    "    float inFront = smoothstep(0.0, 10.0, proj);\n"
    "    \n"
    "    vec3 projectedPos = proj * dir;\n"
    "    float distToAxis = distance(pos, projectedPos);\n"
    "    float coneRadius = proj * 0.35 + 20.0;\n"
    "    float insideCone = smoothstep(coneRadius + 15.0, coneRadius - 15.0, distToAxis);\n"
    "    float inLength = smoothstep(450.0, 400.0, proj);\n"
    "    \n"
    "    float intensity = inFront * insideCone * inLength;\n"
    "    vec3 color = vec3(1.0, 0.9, 0.5);\n"
    "    fragColor = vec4(color * intensity, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_VOLUMETRIC_DUAL_PLANES =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "void main() {\n"
    "    vec3 pos = iPixelPos3D;\n"
    "    float sweepX = 300.0 * sin(time * 1.5);\n"
    "    float d1 = abs(pos.x - sweepX);\n"
    "    float plane1 = smoothstep(15.0, 0.0, d1);\n"
    "    \n"
    "    float sweepZ = 200.0 * cos(time * 2.0);\n"
    "    float d2 = abs(pos.z - sweepZ);\n"
    "    float plane2 = smoothstep(15.0, 0.0, d2);\n"
    "    \n"
    "    float intensity = max(plane1, plane2);\n"
    "    vec3 col1 = vec3(1.0, 0.15, 0.3) * plane1;\n"
    "    vec3 col2 = vec3(0.15, 1.0, 0.4) * plane2;\n"
    "    vec3 color = col1 + col2;\n"
    "    fragColor = vec4(color, 1.0);\n"
    "}\n";

static constexpr const char* GLSL_GENERATIVE_VISUALIZER =
    "#version 150\n"
    "in vec3 vPixelPos3D;\n"
    "in vec2 vPixelPos2D;\n"
    "out vec4 fragColor;\n"
    "#define iPixelPos3D vPixelPos3D\n"
    "#define iPixelPos2D vPixelPos2D\n"
    "uniform float time;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "void main() {\n"
    "    vec2 uv = iPixelPos2D;\n"
    "    float speed = velocity * 2.0;\n"
    "    vec2 warpedUv = uv;\n"
    "    warpedUv.x += sin(uv.y * 10.0 + time * speed) * distortion * 0.2;\n"
    "    warpedUv.y += cos(uv.x * 8.0 + time * speed) * distortion * 0.2;\n"
    "    float zoom = mix(4.0, 20.0, scale);\n"
    "    float val = sin(warpedUv.x * zoom) * sin(warpedUv.y * zoom);\n"
    "    if (complexity > 0.1) {\n"
    "        val += 0.5 * sin(warpedUv.x * zoom * 2.0 + time) * sin(warpedUv.y * zoom * 2.0) * complexity;\n"
    "    }\n"
    "    if (complexity > 0.5) {\n"
    "        val += 0.25 * sin(warpedUv.x * zoom * 4.0 - time) * sin(warpedUv.y * zoom * 4.0) * (complexity - 0.5);\n"
    "    }\n"
    "    float colorPos = val * 0.5 + 0.5;\n"
    "    colorPos = fract(colorPos + asymmetry);\n"
    "    vec4 bgCol = samplePaletteWrapped(colorPos + time * 0.05);\n"
    "    vec3 overlayCol = vec3(0.0);\n"
    "    float overlayAlpha = 0.0;\n"
    "    if (uv.y >= 0.05 && uv.y <= 0.45 && uv.x >= 0.1 && uv.x <= 0.9) {\n"
    "        float barY = (uv.y - 0.05) / 0.4;\n"
    "        int barIdx = int(floor(barY * 6.0));\n"
    "        float localY = fract(barY * 6.0);\n"
    "        if (localY > 0.2 && localY < 0.8) {\n"
    "            float valToCompare = 0.0;\n"
    "            if (barIdx == 5)      valToCompare = velocity;\n"
    "            else if (barIdx == 4) valToCompare = complexity;\n"
    "            else if (barIdx == 3) valToCompare = scale;\n"
    "            else if (barIdx == 2) valToCompare = distortion;\n"
    "            else if (barIdx == 1) valToCompare = asymmetry;\n"
    "            else if (barIdx == 0) valToCompare = intensity;\n"
    "            float localX = (uv.x - 0.1) / 0.8;\n"
    "            if (localX <= valToCompare) {\n"
    "                vec4 barColorSample = samplePalette(float(barIdx) / 5.0);\n"
    "                overlayCol = barColorSample.rgb;\n"
    "                overlayAlpha = 0.85;\n"
    "                if (localX > valToCompare - 0.015) {\n"
    "                    overlayCol += vec3(0.3);\n"
    "                }\n"
    "            } else {\n"
    "                overlayCol = vec3(0.1, 0.1, 0.1);\n"
    "                overlayAlpha = 0.6;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "    vec3 finalCol = bgCol.rgb;\n"
    "    if (overlayAlpha > 0.0) {\n"
    "        finalCol = mix(finalCol, overlayCol, overlayAlpha);\n"
    "    }\n"
    "    finalCol *= intensity;\n"
    "    fragColor = vec4(finalCol, 1.0);\n"
    "}\n";

// ────────────────── Preset Registry ─────────────────────────────

static constexpr Preset kPresets[] = {
    { "Generative Visualizer", GLSL_GENERATIVE_VISUALIZER },
    { "Plasma (default)",    GLSL_PLASMA           },
    { "Horizontal Sweep",    GLSL_HORIZONTAL_SWEEP },
    { "Vertical Chase",      GLSL_VERTICAL_CHASE   },
    { "Rainbow Wave",        GLSL_RAINBOW_WAVE     },
    { "Fire",                GLSL_FIRE             },
    { "Sparkle",             GLSL_SPARKLE          },
    { "Color Solid (cycle)", GLSL_COLOR_SOLID      },
    { "Breathing",           GLSL_BREATHING        },
    { "Strobe",              GLSL_STROBE           },
    { "Volumetric Sphere",   GLSL_VOLUMETRIC_SPHERE},
    { "Volumetric Wave",     GLSL_VOLUMETRIC_WAVE  },
    { "Volumetric Noise",    GLSL_VOLUMETRIC_NOISE },
    { "Volumetric Helix",    GLSL_VOLUMETRIC_HELIX },
    { "3D Breathing Sphere", GLSL_VOLUMETRIC_BREATHING_SPHERE},
    { "3D Spinning Box",     GLSL_VOLUMETRIC_SPINNING_BOX},
    { "3D Cylinder Slicer",  GLSL_VOLUMETRIC_CYLINDER_SLICER},
    { "3D Torus Ring",       GLSL_VOLUMETRIC_TORUS },
    { "3D Spotlight Cone",   GLSL_VOLUMETRIC_CONE  },
    { "3D Dual Planes",      GLSL_VOLUMETRIC_DUAL_PLANES},
};

static constexpr int kPresetCount = (int)(sizeof(kPresets) / sizeof(kPresets[0]));

} // namespace PixelMapper
